## Step 1: Setup environment

Import all required Python libraries and define global settings for this project.

This includes:
- core libraries for data processing (`pandas`, `numpy`)
- utility modules for file paths and date handling
- display settings for easier dataframe inspection in Jupyter

I also define the input data directory and output directory for exported files.

In [1]:
# Step-1: Setup

!pip install "numpy<2" --force-reinstall
import os
import re
import json
import math
import warnings
from pathlib import Path
from datetime import timedelta

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

DATA_DIR = Path("data")
# OUTPUT_DIR = Path("outputs")
# OUTPUT_DIR.mkdir(exist_ok=True)

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)

Collecting numpy<2
  Using cached numpy-1.26.4-cp310-cp310-macosx_10_9_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp310-cp310-macosx_10_9_x86_64.whl (20.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed numpy-1.26.4

## Step 2: Load all source datasets

Load all CSV files into pandas dataframes.

These datasets come from multiple systems:
- HR roster
- TMC bookings
- OBT searches
- flight records
- hotel records
- card transactions
- expense reports
- policy rules
- hotel rate caps
- airport reference table

At this stage, no assumptions are made about data quality.

In [2]:
# Step-2: Load data

# If notebook is inside src/
DATA_DIR = Path("../data").resolve()

print("DATA_DIR =", DATA_DIR)

def read_csv(name):
    path = DATA_DIR / name

    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")

    try:
        df = pd.read_csv(path)
    except UnicodeDecodeError:
        df = pd.read_csv(path, encoding="latin1")

    print(f"{name}: {df.shape}")
    return df


print("\nAvailable CSV files:")
for f in sorted(DATA_DIR.glob("*.csv")):
    print(" -", f.name)

print("\nLoading datasets...\n")

hr = read_csv("hr_employees.csv")
tmc = read_csv("tmc_bookings.csv")
obt = read_csv("obt_searches.csv")
flights = read_csv("flight_segments.csv")
hotels = read_csv("hotel_stays.csv")
cards = read_csv("card_transactions.csv")
expenses = read_csv("expense_reports.csv")
policy_rules = read_csv("travel_policy_rules.csv")
hotel_caps = read_csv("hotel_rate_caps.csv")
airports = read_csv("airports.csv")

print("\nAll datasets loaded successfully.")

# Optional preview
display(hr.head())
display(tmc.head())

DATA_DIR = /Users/kevinchao/data/travel-plan-prediction/data

Available CSV files:
 - airports.csv
 - card_transactions.csv
 - expense_reports.csv
 - flight_segments.csv
 - hotel_rate_caps.csv
 - hotel_stays.csv
 - hr_employees.csv
 - obt_searches.csv
 - tmc_bookings.csv
 - travel_policy_rules.csv

Loading datasets...

hr_employees.csv: (24, 13)
tmc_bookings.csv: (16, 19)
obt_searches.csv: (21, 16)
flight_segments.csv: (33, 18)
hotel_stays.csv: (18, 14)
card_transactions.csv: (45, 14)
expense_reports.csv: (43, 16)
travel_policy_rules.csv: (8, 4)
hotel_rate_caps.csv: (16, 2)
airports.csv: (26, 4)

All datasets loaded successfully.

,employee_id,legal_name,preferred_name,work_email,department,cost_center,manager_id,office_city,country,employment_status,start_date,end_date,title
0,E1001,Maya Chen,Maya,maya.chen@acmebiotech.com,Sales,CC-410 Revenue,E1017,London,GB,Active,2022-04-18,NaN,Enterprise Account Executive
1,E1002,Ethan Patel,Ethan,e.patel@acmebiotech.com,Product,CC-220 Product,E1021,New York,US,Active,2021-09-07,NaN,Senior Product Manager
2,E1003,Sofia Rossi,Sofia,sofia.rossi@acmebiotech.com,Customer Success,CC-510 Customer,E1009,Amsterdam,NL,Active,2020-06-15,NaN,Customer Success Lead
3,E1004,Noah Garcia,Noah,noah.garcia@acmebiotech.com,Sales,CC-410 Revenue,E1017,San Francisco,US,Active,2019-11-04,NaN,Regional Sales Director
4,E1005,Lina Morgan,Lina,lina.morgan@acmebiotech.com,Finance,CC-120 Finance,E1018,London,GB,Active,2023-01-23,NaN,FP&A Manager

,booking_id,traveler_name,traveler_email,traveler_employee_id,booking_date,trip_start_date,trip_end_date,origin_airport,destination_airport,destination_city,record_locator,source_channel,booking_status,itinerary_type,total_booked_amount_usd,currency,trip_purpose,project_code,booking_notes
0,B1001,Maya C.,maya.c@acmebiotech.com,NaN,2025-02-14,2025-03-03,2025-03-08,LHR,SFO,San Francisco,H8M2KQ,OBT,Ticketed,Flight+hotel,2685,USD,Sales kickoff,REV-SK25,Booked through OBT after team kickoff invite.
1,B1002,Ethan Patel,e.patel@acmebiotech.com,E1002,2025-03-06,2025-03-10,2025-03-13,JFK,AUS,Austin,AUS4QP,OBT,Ticketed,Flight+hotel,1775,USD,Product council,PROD-Q2,Selected later departure; see OBT notes.
2,B1003,Sofia Rossi,sofia.rossi@acmebio.com,E1003,2025-03-07,2025-03-15,2025-03-17,AMS,BER,Berlin,BER8CT,Agent,Ticketed,Flight+hotel,840,USD,Client workshop,CUST-BER,Legacy email domain in traveler profile.
3,B1004,Noah Garcia,noah.garcia@acmebiotech.com,E1004,2025-03-03,2025-03-20,2025-03-24,SFO,JFK,New York,NYC2HX,OBT,Ticketed,Flight+hotel,2250,USD,Investor QBR,REV-NYC,QBR itinerary.
4,B1005,Priya S.,priya.s@acmebiotech.com,E1060,2025-03-21,2025-04-02,2025-04-07,BLR,LHR,London,LON7ML,Agent,Ticketed,Flight+hotel,2530,USD,ML summit,ENG-ML,Employee ID typo created during profile migration.

## Step 3: Inspect dataset schemas

Review the shape, columns, and sample rows of each dataset.

The goal here is to:
- understand available linkage signals
- detect missing columns
- verify naming conventions
- identify schema inconsistencies across systems

This step is important because the data is intentionally messy.

In [3]:
# Step-3: Inspect schemas
tables = {
    "hr": hr,
    "tmc": tmc,
    "obt": obt,
    "flights": flights,
    "hotels": hotels,
    "cards": cards,
    "expenses": expenses,
    "policy_rules": policy_rules,
    "hotel_caps": hotel_caps,
    "airports": airports,
}

for name, df in tables.items():
    print("\n" + "=" * 80)
    print(name, df.shape)
    print(df.columns.tolist())
    display(df.head(3))

================================================================================
hr (24, 13)
['employee_id', 'legal_name', 'preferred_name', 'work_email', 'department', 'cost_center', 'manager_id', 'office_city', 'country', 'employment_status', 'start_date', 'end_date', 'title']

,employee_id,legal_name,preferred_name,work_email,department,cost_center,manager_id,office_city,country,employment_status,start_date,end_date,title
0,E1001,Maya Chen,Maya,maya.chen@acmebiotech.com,Sales,CC-410 Revenue,E1017,London,GB,Active,2022-04-18,NaN,Enterprise Account Executive
1,E1002,Ethan Patel,Ethan,e.patel@acmebiotech.com,Product,CC-220 Product,E1021,New York,US,Active,2021-09-07,NaN,Senior Product Manager
2,E1003,Sofia Rossi,Sofia,sofia.rossi@acmebiotech.com,Customer Success,CC-510 Customer,E1009,Amsterdam,NL,Active,2020-06-15,NaN,Customer Success Lead

================================================================================
tmc (16, 19)
['booking_id', 'traveler_name', 'traveler_email', 'traveler_employee_id', 'booking_date', 'trip_start_date', 'trip_end_date', 'origin_airport', 'destination_airport', 'destination_city', 'record_locator', 'source_channel', 'booking_status', 'itinerary_type', 'total_booked_amount_usd', 'currency', 'trip_purpose', 'project_code', 'booking_notes']

,booking_id,traveler_name,traveler_email,traveler_employee_id,booking_date,trip_start_date,trip_end_date,origin_airport,destination_airport,destination_city,record_locator,source_channel,booking_status,itinerary_type,total_booked_amount_usd,currency,trip_purpose,project_code,booking_notes
0,B1001,Maya C.,maya.c@acmebiotech.com,NaN,2025-02-14,2025-03-03,2025-03-08,LHR,SFO,San Francisco,H8M2KQ,OBT,Ticketed,Flight+hotel,2685,USD,Sales kickoff,REV-SK25,Booked through OBT after team kickoff invite.
1,B1002,Ethan Patel,e.patel@acmebiotech.com,E1002,2025-03-06,2025-03-10,2025-03-13,JFK,AUS,Austin,AUS4QP,OBT,Ticketed,Flight+hotel,1775,USD,Product council,PROD-Q2,Selected later departure; see OBT notes.
2,B1003,Sofia Rossi,sofia.rossi@acmebio.com,E1003,2025-03-07,2025-03-15,2025-03-17,AMS,BER,Berlin,BER8CT,Agent,Ticketed,Flight+hotel,840,USD,Client workshop,CUST-BER,Legacy email domain in traveler profile.

================================================================================
obt (21, 16)
['search_id', 'search_timestamp', 'requester_name', 'requester_email', 'origin_airport', 'destination_airport', 'depart_date', 'return_date', 'lowest_airfare_usd', 'selected_airfare_usd', 'selected_hotel_rate_usd', 'policy_status', 'result_count', 'action', 'booking_ref_hint', 'search_notes']

,search_id,search_timestamp,requester_name,requester_email,origin_airport,destination_airport,depart_date,return_date,lowest_airfare_usd,selected_airfare_usd,selected_hotel_rate_usd,policy_status,result_count,action,booking_ref_hint,search_notes
0,S4001,2025-02-04 13:48,Maya Chen,maya.chen@acmebiotech.com,LHR,SFO,2025-03-03,2025-03-08,790,875,285,In policy,42,Booked,H8M2KQ,Selected nonstop despite lower connecting option.
1,S4002,2025-02-17 13:48,Ethan Patel,e.patel@acmebiotech.com,JFK,AUS,2025-03-10,2025-03-13,498,735,280,In policy,31,Booked,AUS4QP,Selected flight arrives before 11:00 workshop.
2,S4003,2025-03-08 09:12,Sofia Rossi,sofia.rossi@acmebiotech.com,AMS,BER,2025-03-15,2025-03-17,295,330,225,In policy,19,Agent booked,BER8CT,Traveler profile had legacy domain.

================================================================================
flights (33, 18)
['segment_id', 'booking_id', 'record_locator', 'traveler_name', 'traveler_email_hint', 'depart_date', 'depart_time', 'arrive_date', 'arrive_time', 'depart_airport', 'arrive_airport', 'carrier', 'flight_number', 'cabin', 'ticket_status', 'ticket_number', 'fare_usd', 'segment_notes']

,segment_id,booking_id,record_locator,traveler_name,traveler_email_hint,depart_date,depart_time,arrive_date,arrive_time,depart_airport,arrive_airport,carrier,flight_number,cabin,ticket_status,ticket_number,fare_usd,segment_notes
0,F1001,B1001,H8M2KQ,Maya C.,NaN,2025-03-03,10:20,2025-03-03,13:55,LHR,SFO,UA,UA900,Economy,Ticketed,160001002.0,437.5,NaN
1,F1002,B1001,H8M2KQ,Maya C.,NaN,2025-03-08,17:10,2025-03-09,11:35,SFO,LHR,UA,UA901,Economy,Ticketed,160001003.0,437.5,NaN
2,F1003,B1002,AUS4QP,Ethan Patel,NaN,2025-03-10,07:05,2025-03-10,10:14,JFK,AUS,DL,DL1234,Economy,Ticketed,160001004.0,367.5,NaN

================================================================================
hotels (18, 14)
['stay_id', 'booking_id', 'traveler_name', 'loyalty_name', 'hotel_name', 'hotel_city', 'check_in', 'check_out', 'nights', 'nightly_rate_usd', 'taxes_fees_usd', 'booking_status', 'source_channel', 'stay_notes']

,stay_id,booking_id,traveler_name,loyalty_name,hotel_name,hotel_city,check_in,check_out,nights,nightly_rate_usd,taxes_fees_usd,booking_status,source_channel,stay_notes
0,H1001,B1001,Maya C.,NaN,Harbor View Union Square,San Francisco,2025-03-03,2025-03-08,5,285,199.5,Confirmed,TMC,NaN
1,H1002,B1002,Ethan Patel,NaN,Austin Central Marriott,Austin,2025-03-10,2025-03-13,3,280,117.6,Confirmed,TMC,NaN
2,H1003,B1003,Sofia Rossi,NaN,Berlin Central Hotel,Berlin,2025-03-15,2025-03-17,2,225,63.0,Confirmed,TMC,NaN

================================================================================
cards (45, 14)
['card_txn_id', 'employee_name_on_card', 'employee_email', 'transaction_date', 'post_date', 'merchant_name', 'merchant_city', 'merchant_country', 'amount_usd', 'currency', 'merchant_category', 'card_last4', 'approval_code', 'card_notes']

,card_txn_id,employee_name_on_card,employee_email,transaction_date,post_date,merchant_name,merchant_city,merchant_country,amount_usd,currency,merchant_category,card_last4,approval_code,card_notes
0,C2001,Maya Chen,maya.chen@acmebiotech.com,2025-02-14,2025-02-16,United Airlines,London,GB,875,USD,Airfare,1001,A371706,NaN
1,C2002,Maya Chen,maya.chen@acmebiotech.com,2025-03-08,2025-03-11,Harbor View Union Square,San Francisco,US,1680,USD,Lodging,1001,A255570,NaN
2,C2003,Maya Chen,maya.chen@acmebiotech.com,2025-03-04,2025-03-05,Lyft,San Francisco,US,62,USD,Ground transport,1001,A235339,NaN

================================================================================
expenses (43, 16)
['expense_line_id', 'report_id', 'submitter_name', 'submitter_email', 'employee_id_reported', 'transaction_date', 'merchant_name', 'city', 'country', 'amount_usd', 'currency', 'expense_category', 'reimbursement_status', 'receipt_text', 'claimed_booking_ref', 'comments']

,expense_line_id,report_id,submitter_name,submitter_email,employee_id_reported,transaction_date,merchant_name,city,country,amount_usd,currency,expense_category,reimbursement_status,receipt_text,claimed_booking_ref,comments
0,X3001,R5001,Maya Chen,maya.chen@acmebiotech.com,E1001,2025-02-14,United Airlines,London,GB,875,USD,Airfare,Approved,UA e-ticket H8M2KQ LHR-SFO return.,H8M2KQ,NaN
1,X3002,R5001,Maya Chen,maya.chen@acmebiotech.com,E1001,2025-03-08,Harbor View Union Square,San Francisco,US,1680,USD,Lodging,Approved,"Hotel folio 5 nights, Harbor View Union Square.",H8M2KQ,NaN
2,X3003,R5001,Maya Chen,maya.chen@acmebiotech.com,E1001,2025-03-04,Lyft,San Francisco,US,62,USD,Ground transport,Approved,Lyft from SFO to hotel.,H8M2KQ,NaN

================================================================================
policy_rules (8, 4)
['rule_id', 'rule_name', 'description', 'severity_hint']

,rule_id,rule_name,description,severity_hint
0,P01,Hotel city cap,"Compare nightly hotel rate to hotel_rate_caps.csv for the destination city. Exceptions can be legitimate, but should...",Medium
1,P02,Advance purchase,Flights should generally be booked at least 7 days before domestic travel and 14 days before international travel. T...,Low
2,P03,Use managed booking channel,"Airfare and hotel spend should usually link back to a TMC booking, OBT search, or clear reason for direct booking.",Medium

================================================================================
hotel_caps (16, 2)
['city', 'max_nightly_rate_usd']

            city  max_nightly_rate_usd
0  San Francisco                   375
1         Austin                   300
2         Berlin                   260

================================================================================
airports (26, 4)
['airport_code', 'airport_name', 'city', 'country']

  airport_code          airport_name           city country
0          LHR       London Heathrow         London      GB
1          SFO    San Francisco Intl  San Francisco      US
2          JFK  John F. Kennedy Intl       New York      US

## Step 4: Define helper functions for cleaning and normalization

Create reusable helper functions for:
- text normalization
- email standardization
- ID cleaning
- date parsing
- keyword detection
- safe numeric conversion

These helpers reduce noise caused by inconsistent formatting across systems.

In [4]:
# Step-4: Normalize helpers
def norm_text(x):
    if pd.isna(x):
        return ""
    return str(x).strip().lower()

def norm_email(x):
    return norm_text(x)

def clean_id(x):
    if pd.isna(x):
        return ""
    return str(x).strip()

def parse_date_cols(df, cols):
    df = df.copy()
    for col in cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
    return df

def contains_any(text, keywords):
    text = norm_text(text)
    return any(k.lower() in text for k in keywords)

def safe_amount(x):
    try:
        return float(x)
    except Exception:
        return np.nan

## Step 5: Standardize date and numeric columns

Convert date-like columns into datetime format and numeric columns into floats.

This ensures:
- reliable date comparisons
- trip window calculations
- amount comparisons across systems

Invalid values are coerced to null instead of causing errors.

In [5]:
# Step-5: Parse dates
tmc = parse_date_cols(tmc, ["trip_start_date", "trip_end_date"])
obt = parse_date_cols(obt, ["search_date", "departure_date", "return_date"])
flights = parse_date_cols(flights, ["depart_date", "arrive_date"])
hotels = parse_date_cols(hotels, ["check_in", "check_out"])
cards = parse_date_cols(cards, ["transaction_date", "post_date"])
expenses = parse_date_cols(expenses, ["transaction_date", "submitted_date"])

for df, amount_cols in [
    (tmc, ["total_booked_amount_usd"]),
    (obt, ["lowest_airfare_usd", "selected_airfare_usd"]),
    (flights, ["fare_usd"]),
    (hotels, ["nightly_rate_usd"]),
    (cards, ["amount_usd"]),
    (expenses, ["amount_usd"]),
]:
    for col in amount_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

## Step 6: Prepare fuzzy matching utilities

Set up fuzzy string matching for approximate name and merchant comparisons.

This helps handle:
- abbreviated names
- nicknames
- typos
- inconsistent merchant labels

Example:
"G Lee" may still match "Grace Lee"

In [6]:
# Step-6: Fuzzy matching helper
try:
    from rapidfuzz import fuzz
    def fuzzy_score(a, b):
        a, b = norm_text(a), norm_text(b)
        if not a or not b:
            return 0.0
        return fuzz.token_sort_ratio(a, b) / 100
except ImportError:
    from difflib import SequenceMatcher
    def fuzzy_score(a, b):
        a, b = norm_text(a), norm_text(b)
        if not a or not b:
            return 0.0
        return SequenceMatcher(None, a, b).ratio()

print("Fuzzy helper ready.")

Fuzzy helper ready.

## Step 7: Build employee identity resolution logic

Create a matching function to map messy traveler identities to canonical HR employees.

The strongest identity signals are:
- employee ID
- work email
- legal name
- preferred name

Each candidate match receives a heuristic confidence score.

In [7]:
# Step-7: HR identity resolver
hr_work = hr.copy()

for col in ["employee_id", "legal_name", "preferred_name", "work_email"]:
    if col not in hr_work.columns:
        hr_work[col] = ""

hr_work["employee_id_norm"] = hr_work["employee_id"].apply(clean_id)
hr_work["work_email_norm"] = hr_work["work_email"].apply(norm_email)
hr_work["legal_name_norm"] = hr_work["legal_name"].apply(norm_text)
hr_work["preferred_name_norm"] = hr_work["preferred_name"].apply(norm_text)

def resolve_employee(name=None, email=None, employee_id=None):
    name = norm_text(name)
    email = norm_email(email)
    employee_id = clean_id(employee_id)

    best = {
        "employee_id": "UNKNOWN",
        "score": 0.0,
        "rationale": "no strong HR match",
    }

    for _, row in hr_work.iterrows():
        score = 0.0
        reasons = []

        if employee_id and employee_id == clean_id(row["employee_id"]):
            score += 0.45
            reasons.append("employee_id")

        if email and email == norm_email(row["work_email"]):
            score += 0.40
            reasons.append("email")

        legal_score = fuzzy_score(name, row["legal_name"])
        pref_score = fuzzy_score(name, row["preferred_name"])
        max_name_score = max(legal_score, pref_score)

        if max_name_score >= 0.92:
            score += 0.20
            reasons.append("strong_name")
        elif max_name_score >= 0.82:
            score += 0.12
            reasons.append("fuzzy_name")

        if score > best["score"]:
            best = {
                "employee_id": row["employee_id"],
                "score": min(score, 1.0),
                "rationale": "+".join(reasons) if reasons else "weak match",
            }

    if best["score"] < 0.25:
        return {
            "employee_id": "UNKNOWN",
            "score": 0.0,
            "rationale": "no strong HR match",
        }

    return best

## Step 8: Create trip anchors from TMC bookings

Use TMC bookings as the primary trip anchors.

I chose TMC as the trip backbone because it usually contains the strongest trip-level information:
- booking ID
- record locator
- traveler identity
- trip start/end dates
- booking status

Each TMC booking gets a unique trip ID.

In [8]:
# Step-8: Create TMC trip anchors
tmc_work = tmc.copy()

tmc_work["trip_id"] = [f"T{i:04d}" for i in range(1, len(tmc_work) + 1)]

tmc_identity = []

for _, row in tmc_work.iterrows():
    resolved = resolve_employee(
        name=row.get("traveler_name"),
        email=row.get("traveler_email"),
        employee_id=row.get("traveler_employee_id"),
    )

    tmc_identity.append({
        "booking_id": row.get("booking_id"),
        "record_locator": row.get("record_locator"),
        "trip_id": row.get("trip_id"),
        "employee_id": resolved["employee_id"],
        "identity_confidence": resolved["score"],
        "identity_rationale": resolved["rationale"],
    })

tmc_identity = pd.DataFrame(tmc_identity)
tmc_work = tmc_work.merge(tmc_identity, on=["booking_id", "record_locator", "trip_id"], how="left")

display(tmc_work.head())

,booking_id,traveler_name,traveler_email,traveler_employee_id,booking_date,trip_start_date,trip_end_date,origin_airport,destination_airport,destination_city,record_locator,source_channel,booking_status,itinerary_type,total_booked_amount_usd,currency,trip_purpose,project_code,booking_notes,trip_id,employee_id,identity_confidence,identity_rationale
0,B1001,Maya C.,maya.c@acmebiotech.com,NaN,2025-02-14,2025-03-03,2025-03-08,LHR,SFO,San Francisco,H8M2KQ,OBT,Ticketed,Flight+hotel,2685,USD,Sales kickoff,REV-SK25,Booked through OBT after team kickoff invite.,T0001,UNKNOWN,0.00,no strong HR match
1,B1002,Ethan Patel,e.patel@acmebiotech.com,E1002,2025-03-06,2025-03-10,2025-03-13,JFK,AUS,Austin,AUS4QP,OBT,Ticketed,Flight+hotel,1775,USD,Product council,PROD-Q2,Selected later departure; see OBT notes.,T0002,E1002,1.00,employee_id+email+strong_name
2,B1003,Sofia Rossi,sofia.rossi@acmebio.com,E1003,2025-03-07,2025-03-15,2025-03-17,AMS,BER,Berlin,BER8CT,Agent,Ticketed,Flight+hotel,840,USD,Client workshop,CUST-BER,Legacy email domain in traveler profile.,T0003,E1003,0.65,employee_id+strong_name
3,B1004,Noah Garcia,noah.garcia@acmebiotech.com,E1004,2025-03-03,2025-03-20,2025-03-24,SFO,JFK,New York,NYC2HX,OBT,Ticketed,Flight+hotel,2250,USD,Investor QBR,REV-NYC,QBR itinerary.,T0004,E1004,1.00,employee_id+email+strong_name
4,B1005,Priya S.,priya.s@acmebiotech.com,E1060,2025-03-21,2025-04-02,2025-04-07,BLR,LHR,London,LON7ML,Agent,Ticketed,Flight+hotel,2530,USD,ML summit,ENG-ML,Employee ID typo created during profile migration.,T0005,UNKNOWN,0.00,no strong HR match

## Step 9: Define trip matching rules

Create the logic to match non-TMC records to existing trips.

Matching signals include:
- record locator
- booking ID
- date overlap
- itinerary overlap
- hotel stay overlap

The goal is to find the best trip candidate for each record.

In [9]:
# Step-9: Link records to TMC trips
def date_near(d, start, end, buffer_days=5):
    if pd.isna(d) or pd.isna(start) or pd.isna(end):
        return False
    return (start - pd.Timedelta(days=buffer_days)) <= d <= (end + pd.Timedelta(days=buffer_days))

def overlap_window(start1, end1, start2, end2, buffer_days=3):
    if pd.isna(start1) or pd.isna(end1) or pd.isna(start2) or pd.isna(end2):
        return False
    return not (
        end1 < start2 - pd.Timedelta(days=buffer_days)
        or start1 > end2 + pd.Timedelta(days=buffer_days)
    )

def best_tmc_match(record, source):
    candidates = []

    for _, trip in tmc_work.iterrows():
        score = 0.0
        reasons = []

        rec_locator = clean_id(record.get("record_locator", ""))
        booking_id = clean_id(record.get("booking_id", ""))
        trip_locator = clean_id(trip.get("record_locator", ""))
        trip_booking_id = clean_id(trip.get("booking_id", ""))

        if rec_locator and trip_locator and rec_locator == trip_locator:
            score += 0.45
            reasons.append("record_locator")

        if booking_id and trip_booking_id and booking_id == trip_booking_id:
            score += 0.45
            reasons.append("booking_id")

        if source == "flight_segments":
            d = record.get("depart_date")
            if date_near(d, trip.get("trip_start_date"), trip.get("trip_end_date"), 2):
                score += 0.20
                reasons.append("flight_date")

        elif source == "hotel_stays":
            if overlap_window(
                record.get("check_in"),
                record.get("check_out"),
                trip.get("trip_start_date"),
                trip.get("trip_end_date"),
                2
            ):
                score += 0.20
                reasons.append("hotel_dates")

        elif source == "obt_searches":
            hint = clean_id(record.get("booking_ref_hint", ""))
            if hint and trip_locator and hint == trip_locator:
                score += 0.45
                reasons.append("booking_ref_hint")

            if date_near(record.get("departure_date"), trip.get("trip_start_date"), trip.get("trip_end_date"), 5):
                score += 0.15
                reasons.append("departure_date")

        candidates.append({
            "trip_id": trip["trip_id"],
            "employee_id": trip["employee_id"],
            "score": min(score, 1.0),
            "rationale": "+".join(reasons),
        })

    best = max(candidates, key=lambda x: x["score"])

    if best["score"] < 0.35:
        return {
            "trip_id": "NO_TRIP",
            "employee_id": "UNKNOWN",
            "score": 0.0,
            "rationale": "no reliable TMC trip match",
        }

    return best

## Step 10: Link trip-related operational records

Link:
- TMC bookings
- flight segments
- hotel stays
- OBT searches

These records provide the strongest evidence for actual travel activity.

In [10]:
# Step-10: Build linked records for TMC, flights, hotels, OBT
linked = []

def add_link(source, record_id, employee_id, trip_id, confidence, rationale):
    linked.append({
        "source": source,
        "record_id": record_id,
        "employee_id": employee_id if employee_id else "UNKNOWN",
        "trip_id": trip_id if trip_id else "NO_TRIP",
        "confidence": round(float(confidence), 2),
        "rationale": rationale,
    })

# TMC bookings
for _, row in tmc_work.iterrows():
    confidence = max(row.get("identity_confidence", 0), 0.75)
    rationale = f"TMC trip anchor; identity={row.get('identity_rationale', '')}"
    add_link(
        "tmc_bookings",
        row.get("booking_id"),
        row.get("employee_id", "UNKNOWN"),
        row.get("trip_id"),
        confidence,
        rationale
    )

# Flights
for _, row in flights.iterrows():
    match = best_tmc_match(row, "flight_segments")
    status = norm_text(row.get("ticket_status"))
    penalty = 0.15 if status in ["canceled", "held"] else 0
    add_link(
        "flight_segments",
        row.get("flight_segment_id", row.get("segment_id", row.get("record_id", ""))),
        match["employee_id"],
        match["trip_id"],
        max(match["score"] - penalty, 0),
        match["rationale"] + (f"; status={status}" if status else "")
    )

# Hotels
for _, row in hotels.iterrows():
    match = best_tmc_match(row, "hotel_stays")
    add_link(
        "hotel_stays",
        row.get("hotel_stay_id", row.get("stay_id", row.get("record_id", ""))),
        match["employee_id"],
        match["trip_id"],
        match["score"],
        match["rationale"]
    )

# OBT searches
for _, row in obt.iterrows():
    match = best_tmc_match(row, "obt_searches")
    action = norm_text(row.get("action"))
    if action in ["abandoned"]:
        match["score"] = min(match["score"], 0.65)
    add_link(
        "obt_searches",
        row.get("search_id", row.get("session_id", row.get("record_id", ""))),
        match["employee_id"],
        match["trip_id"],
        match["score"],
        match["rationale"] + (f"; action={action}" if action else "")
    )

linked_df = pd.DataFrame(linked)
display(linked_df.head(20))

,source,record_id,employee_id,trip_id,confidence,rationale
0,tmc_bookings,B1001,UNKNOWN,T0001,0.75,TMC trip anchor; identity=no strong HR match
1,tmc_bookings,B1002,E1002,T0002,1.00,TMC trip anchor; identity=employee_id+email+strong_name
2,tmc_bookings,B1003,E1003,T0003,0.75,TMC trip anchor; identity=employee_id+strong_name
3,tmc_bookings,B1004,E1004,T0004,1.00,TMC trip anchor; identity=employee_id+email+strong_name
4,tmc_bookings,B1005,UNKNOWN,T0005,0.75,TMC trip anchor; identity=no strong HR match
5,tmc_bookings,B1006,E1007,T0006,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
6,tmc_bookings,B1007,E1008,T0007,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
7,tmc_bookings,B1008,E1009,T0008,0.85,TMC trip anchor; identity=employee_id+email
8,tmc_bookings,B1009,E1010,T0009,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
9,tmc_bookings,B1011,UNKNOWN,T0010,0.75,TMC trip anchor; identity=no strong HR match
10,tmc_bookings,B1012,E1014,T0011,0.75,TMC trip anchor; identity=email+fuzzy_name
11,tmc_bookings,B1013,E1015,T0012,0.85,TMC trip anchor; identity=employee_id+email
12,tmc_bookings,B1014,E1021,T0013,1.00,TMC trip anchor; identity=employee_id+email+strong_name
13,tmc_bookings,B1015,E1022,T0014,1.00,TMC trip anchor; identity=employee_id+email+strong_name
14,tmc_bookings,B1016,E1023,T0015,1.00,TMC trip anchor; identity=employee_id+email+strong_name
15,tmc_bookings,B1018,UNKNOWN,T0016,0.75,TMC trip anchor; identity=no strong HR match
16,flight_segments,F1001,UNKNOWN,T0001,1.00,record_locator+booking_id+flight_date; status=ticketed
17,flight_segments,F1002,UNKNOWN,T0001,1.00,record_locator+booking_id+flight_date; status=ticketed
18,flight_segments,F1003,E1002,T0002,1.00,record_locator+booking_id+flight_date; status=ticketed
19,flight_segments,F1004,E1002,T0002,1.00,record_locator+booking_id+flight_date; status=ticketed

## Step 11: Link card transactions to trips

Match card transactions to employees and trips.

Not every card transaction is travel-related, so I first identify likely travel spend using:
- merchant category
- merchant name
- card notes

Non-travel transactions are assigned `NO_TRIP`.

In [11]:
# Step-11: Link card transactions
travel_mcc_keywords = [
    "air", "airline", "hotel", "lodging", "travel", "taxi", "uber", "lyft",
    "rail", "train", "car rental", "parking"
]

def is_travel_card(row):
    text = " ".join([
        norm_text(row.get("merchant_category", "")),
        norm_text(row.get("merchant_name", "")),
        norm_text(row.get("card_notes", "")),
    ])
    return contains_any(text, travel_mcc_keywords)

def best_card_trip_match(row):
    resolved = resolve_employee(
        name=row.get("employee_name_on_card"),
        email=row.get("employee_email"),
        employee_id=None,
    )

    if not is_travel_card(row):
        return {
            "employee_id": resolved["employee_id"],
            "trip_id": "NO_TRIP",
            "score": 0.80,
            "rationale": "non-travel merchant/category"
        }

    candidates = []

    for _, trip in tmc_work.iterrows():
        score = 0.0
        reasons = []

        if resolved["employee_id"] != "UNKNOWN" and resolved["employee_id"] == trip["employee_id"]:
            score += 0.35
            reasons.append("employee")

        if date_near(row.get("transaction_date"), trip.get("trip_start_date"), trip.get("trip_end_date"), 7):
            score += 0.25
            reasons.append("transaction_date")

        merchant_city = norm_text(row.get("merchant_city"))
        dest = norm_text(trip.get("destination_airport"))
        if merchant_city and merchant_city in norm_text(str(trip.to_dict())):
            score += 0.15
            reasons.append("city_context")

        notes = norm_text(row.get("card_notes"))
        locator = norm_text(trip.get("record_locator"))
        if locator and locator in notes:
            score += 0.30
            reasons.append("locator_in_notes")

        candidates.append({
            "employee_id": trip["employee_id"],
            "trip_id": trip["trip_id"],
            "score": min(score, 1.0),
            "rationale": "+".join(reasons),
        })

    best = max(candidates, key=lambda x: x["score"])

    if best["score"] < 0.45:
        return {
            "employee_id": resolved["employee_id"],
            "trip_id": "NO_TRIP",
            "score": max(0.30, resolved["score"]),
            "rationale": f"travel-like card, no reliable trip match; identity={resolved['rationale']}"
        }

    return best

for _, row in cards.iterrows():
    match = best_card_trip_match(row)
    add_link(
        "card_transactions",
        row.get("card_txn_id"),
        match["employee_id"],
        match["trip_id"],
        match["score"],
        match["rationale"]
    )

linked_df = pd.DataFrame(linked)
display(linked_df[linked_df["source"] == "card_transactions"].head(20))

,source,record_id,employee_id,trip_id,confidence,rationale
88,card_transactions,C2001,E1001,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
89,card_transactions,C2002,E1001,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
90,card_transactions,C2003,E1001,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
91,card_transactions,C2004,E1002,T0002,0.60,employee+transaction_date
92,card_transactions,C2005,E1002,T0002,0.75,employee+transaction_date+city_context
93,card_transactions,C2006,E1002,NO_TRIP,0.80,non-travel merchant/category
94,card_transactions,C2007,E1003,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
95,card_transactions,C2008,E1003,T0003,0.75,employee+transaction_date+city_context
96,card_transactions,C2009,E1004,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
97,card_transactions,C2010,E1004,T0004,0.75,employee+transaction_date+city_context
98,card_transactions,C2011,E1004,NO_TRIP,0.80,non-travel merchant/category
99,card_transactions,C2012,E1006,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
100,card_transactions,C2013,E1006,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
101,card_transactions,C2014,E1007,T0006,0.60,employee+transaction_date
102,card_transactions,C2015,E1007,T0006,0.75,employee+transaction_date+city_context
103,card_transactions,C2016,E1007,T0006,0.75,employee+transaction_date+city_context
104,card_transactions,C2017,E1008,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
105,card_transactions,C2018,E1008,T0007,0.75,employee+transaction_date+city_context
106,card_transactions,C2019,E1009,NO_TRIP,0.60,"travel-like card, no reliable trip match; identity=email+strong_name"
107,card_transactions,C2020,E1009,T0008,0.75,employee+transaction_date+city_context

## Step 12: Link expense reports to trips

Match expense lines to employees and trips using:
- employee identity
- booking references
- transaction dates
- merchant similarity
- receipt text
- comments

Expense records often contain useful unstructured clues.

In [12]:
# Step-12: Link expense reports
def extract_possible_locator(text):
    text = norm_text(text)
    known = tmc_work["record_locator"].dropna().astype(str).str.lower().unique().tolist()
    hits = [loc for loc in known if loc and loc in text]
    return hits[0] if hits else ""

def best_expense_trip_match(row):
    combined_text = " ".join([
        norm_text(row.get("receipt_text", "")),
        norm_text(row.get("claimed_booking_ref", "")),
        norm_text(row.get("comments", "")),
    ])

    resolved = resolve_employee(
        name=row.get("submitter_name"),
        email=row.get("submitter_email"),
        employee_id=row.get("employee_id_reported"),
    )

    locator_hit = extract_possible_locator(combined_text)

    candidates = []

    for _, trip in tmc_work.iterrows():
        score = 0.0
        reasons = []

        if resolved["employee_id"] != "UNKNOWN" and resolved["employee_id"] == trip["employee_id"]:
            score += 0.35
            reasons.append("employee")

        if locator_hit and locator_hit == norm_text(trip.get("record_locator")):
            score += 0.45
            reasons.append("locator_in_expense_text")

        if date_near(row.get("transaction_date"), trip.get("trip_start_date"), trip.get("trip_end_date"), 7):
            score += 0.20
            reasons.append("transaction_date")

        city = norm_text(row.get("city"))
        if city and city in norm_text(str(trip.to_dict())):
            score += 0.15
            reasons.append("city_context")

        candidates.append({
            "employee_id": trip["employee_id"],
            "trip_id": trip["trip_id"],
            "score": min(score, 1.0),
            "rationale": "+".join(reasons),
        })

    best = max(candidates, key=lambda x: x["score"])

    if best["score"] < 0.45:
        return {
            "employee_id": resolved["employee_id"],
            "trip_id": "NO_TRIP",
            "score": max(0.30, resolved["score"]),
            "rationale": f"expense identity only or no reliable trip match; identity={resolved['rationale']}"
        }

    return best

for _, row in expenses.iterrows():
    match = best_expense_trip_match(row)
    add_link(
        "expense_reports",
        row.get("expense_line_id"),
        match["employee_id"],
        match["trip_id"],
        match["score"],
        match["rationale"]
    )

linked_df = pd.DataFrame(linked)
display(linked_df.tail(20))

,source,record_id,employee_id,trip_id,confidence,rationale
156,expense_reports,X3024,E1010,T0009,1.00,employee+locator_in_expense_text+transaction_date+city_context
157,expense_reports,X3025,E1012,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name
158,expense_reports,X3026,E1012,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name
159,expense_reports,X3027,UNKNOWN,T0010,0.45,locator_in_expense_text
160,expense_reports,X3028,UNKNOWN,T0010,0.80,locator_in_expense_text+transaction_date+city_context
161,expense_reports,X3029,E1014,T0011,0.80,employee+locator_in_expense_text
162,expense_reports,X3030,E1014,T0011,1.00,employee+locator_in_expense_text+transaction_date+city_context
163,expense_reports,X3031,E1015,T0012,0.80,employee+locator_in_expense_text
164,expense_reports,X3032,E1015,T0012,1.00,employee+locator_in_expense_text+transaction_date+city_context
165,expense_reports,X3033,E1015,T0012,1.00,employee+locator_in_expense_text+transaction_date+city_context
166,expense_reports,X3034,E1021,T0013,1.00,employee+locator_in_expense_text+transaction_date+city_context
167,expense_reports,X3035,E1022,T0014,0.80,employee+locator_in_expense_text
168,expense_reports,X3036,E1022,T0014,1.00,employee+locator_in_expense_text+transaction_date+city_context
169,expense_reports,X3037,E1023,T0015,0.80,employee+locator_in_expense_text
170,expense_reports,X3038,E1023,T0015,1.00,employee+locator_in_expense_text+transaction_date+city_context
171,expense_reports,X3039,E1018,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name
172,expense_reports,X3040,E1018,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name
173,expense_reports,X3041,E1018,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name
174,expense_reports,X3042,UNKNOWN,T0016,0.60,locator_in_expense_text+city_context
175,expense_reports,X3043,E1005,NO_TRIP,1.00,expense identity only or no reliable trip match; identity=employee_id+email+strong_name

## Step 13: Perform linkage quality checks

Review linkage results to validate:
- coverage by source
- confidence distributions
- trip clustering quality

This provides a quick sanity check before generating review items.

In [13]:
# Step-13: Basic linkage quality checks
print(linked_df.shape)

display(
    linked_df.groupby(["source", "trip_id"])
    .size()
    .reset_index(name="records")
    .sort_values(["source", "records"], ascending=[True, False])
)

display(
    linked_df.groupby("source")["confidence"]
    .describe()
)

(176, 6)

               source  trip_id  records
0   card_transactions  NO_TRIP       29
4   card_transactions    T0006        3
1   card_transactions    T0002        2
7   card_transactions    T0009        2
2   card_transactions    T0003        1
..                ...      ...      ...
90       tmc_bookings    T0012        1
91       tmc_bookings    T0013        1
92       tmc_bookings    T0014        1
93       tmc_bookings    T0015        1
94       tmc_bookings    T0016        1

[95 rows x 3 columns]

                   count      mean       std   min   25%   50%   75%   max
source
card_transactions   45.0  0.655556  0.112423  0.30  0.60  0.60  0.75  0.80
expense_reports     43.0  0.891860  0.160702  0.45  0.80  1.00  1.00  1.00
flight_segments     33.0  0.986364  0.043791  0.85  1.00  1.00  1.00  1.00
hotel_stays         18.0  0.577778  0.210198  0.00  0.65  0.65  0.65  0.65
obt_searches        21.0  0.321429  0.208310  0.00  0.00  0.45  0.45  0.45
tmc_bookings        16.0  0.881875  0.115309  0.75  0.75  0.91  1.00  1.00

## Step 14: Prepare review item framework

Create a helper function to store suspicious findings in a structured review queue.

Each review item includes:
- severity
- issue category
- related records
- explanation
- recommended action

In [14]:
# Step-14: Review item helper
review_items = []

def add_review(category, severity, related_record_ids, summary, recommended_action, confidence):
    review_items.append({
        "rank": None,
        "category": category,
        "severity": severity,
        "related_record_ids": ";".join(related_record_ids),
        "summary": summary,
        "recommended_action": recommended_action,
        "confidence": round(float(confidence), 2),
    })

def src_id(source, rid):
    return f"{source}:{rid}"

## Step 15: Detect inactive employee travel

Flag trips or transactions associated with employees marked inactive in HR.

This may indicate:
- invalid bookings
- stale employee records
- unauthorized spend
- reassignment issues

In [15]:
# Step-15: Review: inactive employee travel
if "employment_status" in hr.columns:
    inactive_ids = set(
        hr.loc[
            hr["employment_status"].astype(str).str.lower().ne("active"),
            "employee_id"
        ].astype(str)
    )

    inactive_links = linked_df[
        linked_df["employee_id"].astype(str).isin(inactive_ids)
        & (linked_df["trip_id"] != "NO_TRIP")
    ]

    for emp_id, g in inactive_links.groupby("employee_id"):
        add_review(
            category="inactive_employee",
            severity="High",
            related_record_ids=[src_id(r.source, r.record_id) for r in g.itertuples()],
            summary=f"Travel-related records are linked to inactive employee {emp_id}.",
            recommended_action="Confirm employment status, travel authorization, and whether charges should be reassigned or investigated.",
            confidence=min(0.95, g["confidence"].max())
        )

len(review_items)

1

## Step 16: Detect held or non-ticketed bookings

Identify TMC bookings that were held but never ticketed.

These records require review because they may represent:
- abandoned bookings
- incomplete travel
- false trip counts

In [16]:
# Step-16: Review: held or not ticketed trips
status_col = "booking_status"

if status_col in tmc.columns:
    held_rows = tmc[
        tmc[status_col].astype(str).str.lower().str.contains("hold|held|not ticketed", na=False)
    ]

    for _, row in held_rows.iterrows():
        rid = row.get("booking_id")
        linked_row = linked_df[
            (linked_df["source"] == "tmc_bookings") &
            (linked_df["record_id"] == rid)
        ]

        related = [src_id("tmc_bookings", rid)]

        add_review(
            category="missing_ticket_or_held_itinerary",
            severity="Medium",
            related_record_ids=related,
            summary=f"TMC booking {rid} appears held or not ticketed.",
            recommended_action="Confirm whether this became a real trip, was abandoned, or should be excluded from spend/trip reporting.",
            confidence=0.85
        )

len(review_items)

2

## Step 17: Detect hotel policy violations

Compare hotel nightly rates against city-level policy caps.

Potential violations may indicate:
- policy exceptions
- out-of-policy bookings
- justified business exceptions

In [17]:
# Step-17: Review: hotel cap violations
if "hotel_city" in hotels.columns and "nightly_rate_usd" in hotels.columns:
    caps_city_col = "city" if "city" in hotel_caps.columns else hotel_caps.columns[0]
    cap_col_candidates = [c for c in hotel_caps.columns if "cap" in c.lower()]
    cap_col = cap_col_candidates[0] if cap_col_candidates else None

    if cap_col:
        hotel_check = hotels.merge(
            hotel_caps,
            left_on=hotels["hotel_city"].astype(str).str.lower(),
            right_on=hotel_caps[caps_city_col].astype(str).str.lower(),
            how="left",
            suffixes=("", "_cap")
        )

        violations = hotel_check[
            hotel_check["nightly_rate_usd"] > hotel_check[cap_col]
        ]

        for _, row in violations.iterrows():
            rid = row.get("hotel_stay_id", row.get("stay_id", row.get("record_id", "")))
            add_review(
                category="hotel_rate_cap_exceeded",
                severity="Medium",
                related_record_ids=[src_id("hotel_stays", rid)],
                summary=f"Hotel nightly rate ${row['nightly_rate_usd']:.2f} exceeds cap ${row[cap_col]:.2f} for {row.get('hotel_city')}.",
                recommended_action="Review for business justification, approved exception, conference rate, or traveler reimbursement adjustment.",
                confidence=0.90
            )

len(review_items)

2

## Step 18: Detect possible duplicate reimbursement

Search for card transactions and expense lines with:
- similar merchant
- similar dates
- similar amounts

These may represent duplicate reimbursement risks.

In [18]:
# Step-18: Review: duplicate card and expense claims
card_expense_pairs = []

for _, c in cards.iterrows():
    for _, x in expenses.iterrows():
        same_amount = (
            pd.notna(c.get("amount_usd")) and
            pd.notna(x.get("amount_usd")) and
            abs(float(c["amount_usd"]) - float(x["amount_usd"])) <= 1.00
        )

        close_date = False
        if pd.notna(c.get("transaction_date")) and pd.notna(x.get("transaction_date")):
            close_date = abs((c["transaction_date"] - x["transaction_date"]).days) <= 3

        merchant_sim = fuzzy_score(c.get("merchant_name"), x.get("merchant_name"))

        if same_amount and close_date and merchant_sim >= 0.75:
            card_expense_pairs.append((c, x, merchant_sim))

for c, x, sim in card_expense_pairs:
    add_review(
        category="possible_duplicate_expense",
        severity="High",
        related_record_ids=[
            src_id("card_transactions", c.get("card_txn_id")),
            src_id("expense_reports", x.get("expense_line_id")),
        ],
        summary=f"Card transaction and expense line have similar merchant, date, and amount ${c.get('amount_usd')}.",
        recommended_action="Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.",
        confidence=0.85
    )

len(review_items)

44

## Step 19: Detect refunds and credits

Identify negative card transactions that may represent:
- ticket refunds
- exchanges
- credits
- cancellations

These need reconciliation with original charges.

In [19]:
# Step-19: Review: refunds and negative card transactions
negative_cards = cards[cards["amount_usd"] < 0] if "amount_usd" in cards.columns else pd.DataFrame()

for _, row in negative_cards.iterrows():
    emp = resolve_employee(
        name=row.get("employee_name_on_card"),
        email=row.get("employee_email")
    )

    possible_original = cards[
        (cards["amount_usd"] > 0) &
        (cards["employee_email"].astype(str).str.lower() == str(row.get("employee_email")).lower()) &
        (cards["merchant_name"].apply(lambda x: fuzzy_score(x, row.get("merchant_name"))) >= 0.70)
    ]

    confidence = 0.75 if len(possible_original) == 0 else 0.55

    add_review(
        category="refund_or_credit_review",
        severity="Medium",
        related_record_ids=[src_id("card_transactions", row.get("card_txn_id"))],
        summary=f"Negative card transaction ${row.get('amount_usd')} may be refund/credit requiring reconciliation.",
        recommended_action="Match credit to original charge, exchange, cancellation, or expense adjustment.",
        confidence=confidence
    )

len(review_items)

45

## Step 20: Detect possible out-of-channel bookings

Find travel-related card spend that does not match any managed trip.

This may indicate direct bookings outside the managed travel program.

In [20]:
# Step-20: Review: direct travel spend with no trip
card_links = linked_df[
    (linked_df["source"] == "card_transactions") &
    (linked_df["trip_id"] == "NO_TRIP")
]

for _, link in card_links.iterrows():
    card_row = cards[cards["card_txn_id"] == link["record_id"]]
    if card_row.empty:
        continue

    row = card_row.iloc[0]

    if is_travel_card(row):
        add_review(
            category="possible_direct_booking",
            severity="Medium",
            related_record_ids=[src_id("card_transactions", link["record_id"])],
            summary="Travel-like card transaction was not linked to a managed TMC trip.",
            recommended_action="Review whether this was an out-of-channel/direct booking or should be linked to an existing trip.",
            confidence=0.70
        )

len(review_items)

69

## Step 21: Rank review items

Sort all review items by:
1. severity
2. confidence

This produces a prioritized queue for finance or travel operations review.

In [21]:
# Step-21: Rank review items
severity_rank = {
    "High": 3,
    "Medium": 2,
    "Low": 1,
}

review_df = pd.DataFrame(review_items)

if len(review_df) > 0:
    review_df["_severity_rank"] = review_df["severity"].map(severity_rank).fillna(0)
    review_df = review_df.sort_values(
        ["_severity_rank", "confidence"],
        ascending=[False, False]
    ).drop(columns=["_severity_rank"])
    review_df["rank"] = range(1, len(review_df) + 1)

display(review_df.head(10))

,rank,category,severity,related_record_ids,summary,recommended_action,confidence
0,1,inactive_employee,High,tmc_bookings:B1007;flight_segments:F1013;flight_segments:F1014;hotel_stays:H1007;obt_searches:S4007;card_transaction...,Travel-related records are linked to inactive employee E1008.,"Confirm employment status, travel authorization, and whether charges should be reassigned or investigated.",0.95
2,2,possible_duplicate_expense,High,card_transactions:C2001;expense_reports:X3001,"Card transaction and expense line have similar merchant, date, and amount $875.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
3,3,possible_duplicate_expense,High,card_transactions:C2002;expense_reports:X3002,"Card transaction and expense line have similar merchant, date, and amount $1680.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
4,4,possible_duplicate_expense,High,card_transactions:C2003;expense_reports:X3003,"Card transaction and expense line have similar merchant, date, and amount $62.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
5,5,possible_duplicate_expense,High,card_transactions:C2004;expense_reports:X3004,"Card transaction and expense line have similar merchant, date, and amount $735.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
6,6,possible_duplicate_expense,High,card_transactions:C2005;expense_reports:X3005,"Card transaction and expense line have similar merchant, date, and amount $840.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
7,7,possible_duplicate_expense,High,card_transactions:C2006;expense_reports:X3006,"Card transaction and expense line have similar merchant, date, and amount $86.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
8,8,possible_duplicate_expense,High,card_transactions:C2007;expense_reports:X3007,"Card transaction and expense line have similar merchant, date, and amount $330.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
9,9,possible_duplicate_expense,High,card_transactions:C2008;expense_reports:X3008,"Card transaction and expense line have similar merchant, date, and amount $510.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
10,10,possible_duplicate_expense,High,card_transactions:C2008;expense_reports:X3009,"Card transaction and expense line have similar merchant, date, and amount $510.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85

## Step 22: Export required deliverables

Export the two required submission files:
- linked_records.csv
- review_items.csv

Also verify that all required columns are present.

In [22]:
# Step-22: Export required CSVs
# If running inside ~/src/
OUTPUT_DIR = Path("../outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

required_link_cols = [
    "source",
    "record_id",
    "employee_id",
    "trip_id",
    "confidence",
    "rationale",
]

required_review_cols = [
    "rank",
    "category",
    "severity",
    "related_record_ids",
    "summary",
    "recommended_action",
    "confidence",
]

# Keep only required columns
linked_df = linked_df[required_link_cols].copy()

review_df = (
    review_df[required_review_cols].copy()
    if len(review_df) > 0
    else pd.DataFrame(columns=required_review_cols)
)

# Output file paths
linked_path = OUTPUT_DIR / "linked_records.csv"
review_path = OUTPUT_DIR / "review_items.csv"

# Save CSVs
linked_df.to_csv(linked_path, index=False)
review_df.to_csv(review_path, index=False)

print(f"Wrote: {linked_path.resolve()}")
print(f"Wrote: {review_path.resolve()}")

display(linked_df.head())
display(review_df.head())

Wrote: /Users/kevinchao/data/travel-plan-prediction/outputs/linked_records.csv
Wrote: /Users/kevinchao/data/travel-plan-prediction/outputs/review_items.csv

,source,record_id,employee_id,trip_id,confidence,rationale
0,tmc_bookings,B1001,UNKNOWN,T0001,0.75,TMC trip anchor; identity=no strong HR match
1,tmc_bookings,B1002,E1002,T0002,1.00,TMC trip anchor; identity=employee_id+email+strong_name
2,tmc_bookings,B1003,E1003,T0003,0.75,TMC trip anchor; identity=employee_id+strong_name
3,tmc_bookings,B1004,E1004,T0004,1.00,TMC trip anchor; identity=employee_id+email+strong_name
4,tmc_bookings,B1005,UNKNOWN,T0005,0.75,TMC trip anchor; identity=no strong HR match

,rank,category,severity,related_record_ids,summary,recommended_action,confidence
0,1,inactive_employee,High,tmc_bookings:B1007;flight_segments:F1013;flight_segments:F1014;hotel_stays:H1007;obt_searches:S4007;card_transaction...,Travel-related records are linked to inactive employee E1008.,"Confirm employment status, travel authorization, and whether charges should be reassigned or investigated.",0.95
2,2,possible_duplicate_expense,High,card_transactions:C2001;expense_reports:X3001,"Card transaction and expense line have similar merchant, date, and amount $875.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
3,3,possible_duplicate_expense,High,card_transactions:C2002;expense_reports:X3002,"Card transaction and expense line have similar merchant, date, and amount $1680.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
4,4,possible_duplicate_expense,High,card_transactions:C2003;expense_reports:X3003,"Card transaction and expense line have similar merchant, date, and amount $62.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
5,5,possible_duplicate_expense,High,card_transactions:C2004;expense_reports:X3004,"Card transaction and expense line have similar merchant, date, and amount $735.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85

## Step 23: Final validation

Run final checks to ensure:
- output files exist
- schemas are correct
- confidence values are valid
- deliverables are submission-ready

In [23]:
# Step-23: Final validation
print("linked_records.csv")
print(linked_df.shape)
display(linked_df.head(10))

print("\nreview_items.csv")
print(review_df.shape)
display(review_df.head(10))

assert set(required_link_cols).issubset(linked_df.columns)
assert set(required_review_cols).issubset(review_df.columns)

assert linked_df["confidence"].between(0, 1).all()
if len(review_df) > 0:
    assert review_df["confidence"].between(0, 1).all()

print("Validation passed.")

linked_records.csv
(176, 6)

,source,record_id,employee_id,trip_id,confidence,rationale
0,tmc_bookings,B1001,UNKNOWN,T0001,0.75,TMC trip anchor; identity=no strong HR match
1,tmc_bookings,B1002,E1002,T0002,1.00,TMC trip anchor; identity=employee_id+email+strong_name
2,tmc_bookings,B1003,E1003,T0003,0.75,TMC trip anchor; identity=employee_id+strong_name
3,tmc_bookings,B1004,E1004,T0004,1.00,TMC trip anchor; identity=employee_id+email+strong_name
4,tmc_bookings,B1005,UNKNOWN,T0005,0.75,TMC trip anchor; identity=no strong HR match
5,tmc_bookings,B1006,E1007,T0006,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
6,tmc_bookings,B1007,E1008,T0007,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
7,tmc_bookings,B1008,E1009,T0008,0.85,TMC trip anchor; identity=employee_id+email
8,tmc_bookings,B1009,E1010,T0009,0.97,TMC trip anchor; identity=employee_id+email+fuzzy_name
9,tmc_bookings,B1011,UNKNOWN,T0010,0.75,TMC trip anchor; identity=no strong HR match

review_items.csv
(69, 7)

,rank,category,severity,related_record_ids,summary,recommended_action,confidence
0,1,inactive_employee,High,tmc_bookings:B1007;flight_segments:F1013;flight_segments:F1014;hotel_stays:H1007;obt_searches:S4007;card_transaction...,Travel-related records are linked to inactive employee E1008.,"Confirm employment status, travel authorization, and whether charges should be reassigned or investigated.",0.95
2,2,possible_duplicate_expense,High,card_transactions:C2001;expense_reports:X3001,"Card transaction and expense line have similar merchant, date, and amount $875.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
3,3,possible_duplicate_expense,High,card_transactions:C2002;expense_reports:X3002,"Card transaction and expense line have similar merchant, date, and amount $1680.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
4,4,possible_duplicate_expense,High,card_transactions:C2003;expense_reports:X3003,"Card transaction and expense line have similar merchant, date, and amount $62.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
5,5,possible_duplicate_expense,High,card_transactions:C2004;expense_reports:X3004,"Card transaction and expense line have similar merchant, date, and amount $735.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
6,6,possible_duplicate_expense,High,card_transactions:C2005;expense_reports:X3005,"Card transaction and expense line have similar merchant, date, and amount $840.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
7,7,possible_duplicate_expense,High,card_transactions:C2006;expense_reports:X3006,"Card transaction and expense line have similar merchant, date, and amount $86.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
8,8,possible_duplicate_expense,High,card_transactions:C2007;expense_reports:X3007,"Card transaction and expense line have similar merchant, date, and amount $330.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
9,9,possible_duplicate_expense,High,card_transactions:C2008;expense_reports:X3008,"Card transaction and expense line have similar merchant, date, and amount $510.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85
10,10,possible_duplicate_expense,High,card_transactions:C2008;expense_reports:X3009,"Card transaction and expense line have similar merchant, date, and amount $510.",Check whether the expense is a reconciliation of the corporate card charge or a duplicate reimbursement request.,0.85

Validation passed.